diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.editor="C:\\Program Files\\Microsoft VS Code\\bin\\code" --wait
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=User
user.email=jonzarmar@gmail.com
credential.helper=manager
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
branch.v4.vscode-merge-base=origin/v4
remote.upstream.url=https://github.com/jackyzha0/quartz.git
remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
remote.origin.url=https://github.com/LostName1/notas.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
